#!/usr/bin/env python3
"""ProfitCalc Build — Profit calculators for eCommerce sellers"""

import os
os.chdir(os.path.dirname(os.path.abspath(__file__)))

DOMAIN = "calcprofit.net"

def w(path, content):
    full = os.path.join(".", path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as f:
        f.write(content)

def build_page(s, is_home=False):
    title = s.get("title", "")
    desc = s.get("desc", "")
    slug = s.get("slug", "")
    fields = s.get("fields", [])  # [{id, label, placeholder, prefix, suffix}]
    formula_text = s.get("formula", "")

    field_html = ""
    for f in fields:
        fid = f["id"]
        label = f.get("label", fid)
        placeholder = f.get("placeholder", "")
        prefix = f.get("prefix", "")
        suffix = f.get("suffix", "")
        field_html += f'''<div class="field">
            <label for="{fid}">{label}</label>
            <div class="input-wrap">
                {f'<span class="prefix">{prefix}</span>' if prefix else ''}
                <input id="{fid}" placeholder="{placeholder}" type="number" step="0.01" oninput="calc()">
                {f'<span class="suffix">{suffix}</span>' if suffix else ''}
            </div>
        </div>'''

    result_html = s.get("results", [])
    result_cards = ""
    if result_html:
        result_cards = '<div class="result-grid">'
        for r in result_html:
            rid = r["id"]
            rlabel = r["label"]
            rprefix = r.get("prefix", "$")
            result_cards += f'''<div class="result-card">
                <div class="result-label">{rlabel}</div>
                <div class="result-value" id="{rid}">{rprefix}0.00</div>
            </div>'''
        result_cards += '</div>'

    platform_cards = ""
    if is_home:
        platform_cards = '<div class="tool-grid">'
        for p in PLATFORMS:
            platform_cards += f'''<a href="/{p["slug"]}/" class="tool-card">
                <h3>{p["title"]}</h3>
                <p>{p["desc"][:80]}...</p>
            </a>'''
        platform_cards += '</div>'

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{desc}">
    <meta name="robots" content="index, follow">
    <meta property="og:title" content="{title} | ProfitCalc">
    <meta property="og:description" content="{desc}">
    <link rel="canonical" href="https://{DOMAIN}/{slug}/">
    <title>{title} | ProfitCalc</title>
    <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">
    <style>
        :root{{--bg:#FFF8F0;--card:#FFFDFA;--border:#F3E8D8;--text:#1C1917;--muted:#78716C;--primary:#D97706;--primary-hover:#B45309;--radius:16px}}
        *{{box-sizing:border-box;margin:0;padding:0}}
        body{{font-family:'DM Sans',-apple-system,sans-serif;background:var(--bg);color:var(--text);line-height:1.6}}
        nav{{position:sticky;top:0;background:#FFFAF5;backdrop-filter:blur(8px);border-bottom:1px solid var(--border);padding:14px 24px;display:flex;justify-content:space-between;z-index:100}}
        .logo{{font-weight:700;color:var(--primary);font-size:1.2rem;text-decoration:none}}
        .nav-links{{display:flex;gap:20px;align-items:center}}
        .nav-links a{{color:var(--muted);text-decoration:none;font-size:0.9rem;font-weight:500}}
        .nav-links a:hover{{color:var(--text)}}
        .container{{max-width:1100px;margin:0 auto;padding:0 24px}}
        .hero{{text-align:center;padding:48px 0 32px}}
        .hero h1{{font-size:2rem;font-weight:700;margin-bottom:12px;letter-spacing:-0.02em}}
        .hero p{{color:var(--muted);max-width:560px;margin:0 auto;font-size:1rem}}
        .tool-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:32px 0 48px}}
        @media(max-width:768px){{.tool-grid{{grid-template-columns:1fr}}}} 
        .tool-card{{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:20px;text-decoration:none;color:var(--text);transition:all .15s;box-shadow:0 1px 3px rgba(0,0,0,0.04)}}
        .tool-card:hover{{border-color:var(--primary);box-shadow:0 4px 12px rgba(217,119,6,0.12);transform:translateY(-2px)}}
        .tool-card h3{{font-size:1.05rem;margin-bottom:6px}}
        .tool-card p{{font-size:0.85rem;color:var(--muted)}}
        .calc-section{{max-width:680px;margin:0 auto;padding:40px 0}}
        .calc-card{{background:var(--card);border:1px solid var(--border);border-radius:var(--radius);padding:28px;box-shadow:0 2px 8px rgba(0,0,0,0.05)}}
        .field{{margin-bottom:14px}}
        .field label{{display:block;font-size:0.85rem;font-weight:600;margin-bottom:4px;color:var(--text)}}
        .input-wrap{{display:flex;align-items:center;border:1px solid var(--border);border-radius:10px;overflow:hidden;background:var(--bg);transition:border-color .15s}}
        .input-wrap:focus-within{{border-color:var(--primary)}}
        .prefix,.suffix{{padding:10px 12px;background:#F5F1EB;color:var(--muted);font-size:0.9rem;font-weight:500;white-space:nowrap}}
        .input-wrap input{{flex:1;border:none;padding:10px 12px;background:transparent;color:var(--text);font-family:inherit;font-size:1rem;outline:none;min-width:0}}
        .result-grid{{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-top:20px;padding-top:20px;border-top:1px solid var(--border)}}
        @media(max-width:640px){{.result-grid{{grid-template-columns:1fr}}}}
        .result-card{{text-align:center;padding:14px;background:var(--bg);border-radius:10px}}
        .result-label{{font-size:0.8rem;color:var(--muted);margin-bottom:4px}}
        .result-value{{font-size:1.5rem;font-weight:700;color:var(--primary)}}
        .content-section{{max-width:680px;margin:40px auto;padding:0 24px}}
        .content-section h2{{font-size:1.2rem;margin:24px 0 10px}}
        .content-section p{{color:var(--muted);margin-bottom:12px;font-size:0.95rem;line-height:1.7}}
        .cross-link{{margin:40px auto;max-width:680px;padding:20px;background:#FFF7ED;border:1px solid var(--primary);border-radius:12px}}
        .cross-link strong{{color:var(--primary)}}
        .cross-link a{{color:var(--primary);font-weight:500}}
        .breadcrumb{{font-size:0.85rem;color:var(--muted);margin-bottom:16px}}
        .breadcrumb a{{color:var(--primary);text-decoration:none}}
        footer{{background:#1C1917;color:#A8A29E;padding:32px;text-align:center;font-size:0.85rem;margin-top:60px}}
        footer a{{color:#FB923C;text-decoration:none}}
    </style>
    <script type="application/ld+json">
    {{"@context":"https://schema.org","@type":"SoftwareApplication","name":"{title}","url":"https://{DOMAIN}/{slug}/","description":"{desc}","applicationCategory":"FinanceApplication","operatingSystem":"All","offers":{{"@type":"Offer","price":"0","priceCurrency":"USD"}}}}
    </script>
    <script type="application/ld+json">
    {{"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{{"@type":"Question","name":"How do I calculate profit margin?","acceptedAnswer":{{"@type":"Answer","text":"Profit margin = (Revenue - Total Costs) / Revenue × 100. Use our free calculator above."}}}},{{"@type":"Question","name":"Is ProfitCalc free?","acceptedAnswer":{{"@type":"Answer","text":"Yes, completely free. No sign-up required. Calculate unlimited profits."}}}},{{"@type":"Question","name":"What platforms does ProfitCalc support?","acceptedAnswer":{{"@type":"Answer","text":"Amazon FBA, Etsy, eBay, Shopify, Dropshipping, and general business profit calculation."}}}}]}}
    </script>
    <script type="application/ld+json">
    {{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"Home","item":"https://{DOMAIN}/"}},{{"@type":"ListItem","position":2,"name":"{title}","item":"https://{DOMAIN}/{slug}/"}}]}}
    </script>
<script async src="https://www.googletagmanager.com/gtag/js?id=G-Z9NW1GSG04"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments);}}gtag("js",new Date());gtag("config","G-Z9NW1GSG04");</script></head>
<body>
    <nav>
        <a href="/" class="logo">ProfitCalc</a>
        <div class="nav-links">
            <a href="/">Home</a>
            <a href="#calculator">Calculator</a>
            <a href="#faq">FAQ</a>
        </div>
    </nav>
    {f'<div class="container hero"><h1>{title}</h1><p>{desc}</p></div>' if is_home else f'<div class="container"><div class="breadcrumb"><a href="/">Home</a> / {title}</div><h1 style="font-size:1.75rem;font-weight:700;margin:24px 0 8px">{title}</h1><p style="color:var(--muted);margin-bottom:24px">{desc}</p></div>'}
    {platform_cards}
    <div class="calc-section" id="calculator">
        <div class="calc-card">
            {field_html}
            {result_cards}
        </div>
    </div>
    <div class="content-section">
        <h2>What is ProfitCalc?</h2>
        <p>ProfitCalc is a free profit calculator for eCommerce sellers. Calculate your profit margins, fees, and ROI for Amazon FBA, Etsy, eBay, Shopify, and dropshipping businesses. Use ProfitCalc to make smarter pricing decisions — your go-to profit calculator for online sellers.</p>
        <h2>How It Works</h2>
        <p>Step 1: Enter your selling price and cost. Step 2: Add platform fees, shipping, and ad costs. Step 3: Instantly see your profit, margin, and ROI. It's that simple.</p>
        <h2>Common Use Cases</h2>
        <p>ProfitCalc is used by Amazon FBA sellers, Etsy shop owners, eBay resellers, Shopify merchants, and dropshipping entrepreneurs to calculate profitability before listing products.</p>
        {f'<h2>About {title}</h2><p>{desc} Built for sellers who need accurate profit calculations fast.</p>' if not is_home else ''}
    </div>
    <div class="cross-link">
        <strong>Recommended Tools</strong> — Start selling online: <a href="https://www.shopify.com/free-trial" rel="nofollow sponsored">Shopify Free Trial</a>. Scale your Amazon business: <a href="https://www.helium10.com" rel="nofollow sponsored">Helium 10</a>. Need a store built? <a href="https://www.fiverr.com/search/gigs?query=shopify+store+builder" rel="nofollow sponsored">Fiverr Store Builders</a>. Also try our free tools: <a href="https://tracklinks.net">TrackLinks</a> for UTM tracking, <a href="https://compressnow.net">CompressNow</a> for image compression. Optimize your entire seller workflow with our free tool suite.
    </div>
    <div class="content-section" id="faq">
        <h2>Frequently Asked Questions</h2>
        <p><strong>Q: How accurate is the profit calculation?</strong><br>A: The calculator uses the standard profit formula. Actual platform fees may vary — always verify with your platform's fee schedule.</p>
        <p><strong>Q: Is ProfitCalc free?</strong><br>A: Yes, 100% free with no sign-up and no limits on calculations.</p>
        <p><strong>Q: Can I use this for my Amazon FBA business?</strong><br>A: Yes — our Amazon FBA calculator includes FBA fees, referral fees, and PPC ad costs.</p>
        <p><strong>Q: What's the difference between profit margin and ROI?</strong><br>A: Profit margin = Profit / Revenue. ROI = Profit / Investment Cost. Both are useful — margin tells you pricing efficiency, ROI tells you return on your capital.</p>
    </div>
    <footer>
        <p>ProfitCalc — Free Profit Calculator for eCommerce Sellers. Amazon, Etsy, eBay, Shopify, Dropshipping.</p>
        <p style="margin-top:8px"><a href="/">Home</a> · <a href="https://compressnow.net">CompressNow</a> · <a href="https://tracklinks.net">TrackLinks</a> · <a href="https://resizenow.net">ResizeNow</a></p>
    </footer>
    <script>
    function getVal(id){{return parseFloat(document.getElementById(id).value)||0;}}
    function calc(){{
        {s.get('calc_js', '')}
    }}
    calc();
    </script>
</body>
</html>"""

# ═══ Common calc JS ═══════════════════════════════

PROFIT_CALC_JS = """
var price=getVal('price'),cost=getVal('cost'),shipping=getVal('shipping'),fee=getVal('fee'),ads=getVal('ads');
var revenue=price;
var feeAmt=revenue*(fee/100);
var totalCost=cost+shipping+feeAmt+ads;
var profit=revenue-totalCost;
var margin=revenue>0?(profit/revenue*100):0;
var roi=totalCost>0?(profit/totalCost*100):0;
document.getElementById('profit').innerText='$'+profit.toFixed(2);
document.getElementById('margin').innerText=margin.toFixed(1)+'%';
document.getElementById('roi').innerText=roi.toFixed(1)+'%';
"""

# ═══ Page Definitions ═══════════════════════════════

PLATFORMS = [
    {"slug":"amazon-fba","title":"Amazon FBA Profit Calculator","desc":"Calculate Amazon FBA profits including referral fees, FBA fees, and PPC ad costs. Free tool for Amazon sellers.","fields":[
        {"id":"price","label":"Selling Price","placeholder":"29.99","prefix":"$"},
        {"id":"cost","label":"Product Cost","placeholder":"8.00","prefix":"$"},
        {"id":"shipping","label":"FBA Shipping Cost","placeholder":"3.00","prefix":"$"},
        {"id":"fee","label":"Amazon Referral Fee (%)","placeholder":"15","suffix":"%"},
        {"id":"ads","label":"PPC Ads Cost per Unit","placeholder":"2.00","prefix":"$"},
    ],"results":[
        {"id":"profit","label":"Net Profit","prefix":"$"},
        {"id":"margin","label":"Profit Margin","prefix":""},
        {"id":"roi","label":"ROI","prefix":""},
    ],"formula":"Profit = Price - (Cost + FBA + Referral Fee% + Ads)","calc_js":PROFIT_CALC_JS},
    
    {"slug":"etsy","title":"Etsy Fee & Profit Calculator","desc":"Calculate Etsy profits after listing fees, transaction fees, and payment processing. Free Etsy seller tool.","fields":[
        {"id":"price","label":"Selling Price","placeholder":"25.00","prefix":"$"},
        {"id":"cost","label":"Material & Production Cost","placeholder":"10.00","prefix":"$"},
        {"id":"shipping","label":"Shipping Cost","placeholder":"4.00","prefix":"$"},
        {"id":"fee","label":"Etsy Transaction Fee (%)","placeholder":"6.5","suffix":"%"},
        {"id":"ads","label":"Etsy Ads Cost","placeholder":"0.00","prefix":"$"},
    ],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"formula":"Profit = Price - (Cost + Shipping + Etsy Fee% + Ads)","calc_js":PROFIT_CALC_JS},
    
    {"slug":"ebay","title":"eBay Profit Calculator","desc":"Calculate eBay selling profits including final value fees and shipping. Free tool for eBay resellers.","fields":[
        {"id":"price","label":"Selling Price","placeholder":"20.00","prefix":"$"},
        {"id":"cost","label":"Cost of Goods","placeholder":"8.00","prefix":"$"},
        {"id":"shipping","label":"Shipping Cost","placeholder":"5.00","prefix":"$"},
        {"id":"fee","label":"eBay Final Value Fee (%)","placeholder":"13.25","suffix":"%"},
        {"id":"ads","label":"Promoted Listing Cost","placeholder":"0.00","prefix":"$"},
    ],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"formula":"Profit = Price - (Cost + Shipping + eBay Fee% + Promoted)","calc_js":PROFIT_CALC_JS},
    
    {"slug":"shopify","title":"Shopify Profit Margin Calculator","desc":"Calculate Shopify store profits after payment processing and app fees. Free tool for Shopify merchants.","fields":[
        {"id":"price","label":"Selling Price","placeholder":"49.99","prefix":"$"},
        {"id":"cost","label":"Product & Fulfillment Cost","placeholder":"20.00","prefix":"$"},
        {"id":"shipping","label":"Shipping Cost","placeholder":"5.00","prefix":"$"},
        {"id":"fee","label":"Payment Processing Fee (%)","placeholder":"2.9","suffix":"%"},
        {"id":"ads","label":"Marketing & App Costs","placeholder":"5.00","prefix":"$"},
    ],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"formula":"Profit = Price - (Cost + Shipping + Payment Fee% + Marketing)","calc_js":PROFIT_CALC_JS},
    
    {"slug":"dropshipping","title":"Dropshipping Profit Calculator","desc":"Calculate dropshipping profits including supplier cost, shipping, and ad spend. Free tool for dropshippers.","fields":[
        {"id":"price","label":"Selling Price","placeholder":"39.99","prefix":"$"},
        {"id":"cost","label":"Supplier Cost","placeholder":"12.00","prefix":"$"},
        {"id":"shipping","label":"Shipping & Handling","placeholder":"3.00","prefix":"$"},
        {"id":"fee","label":"Platform Fee (%)","placeholder":"5","suffix":"%"},
        {"id":"ads","label":"Facebook/Google Ads per Unit","placeholder":"8.00","prefix":"$"},
    ],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"formula":"Profit = Price - (Supplier Cost + Shipping + Fee% + Ads)","calc_js":PROFIT_CALC_JS},
    
    {"slug":"small-business","title":"Small Business Profit Calculator","desc":"Calculate profit margins for any small business or product. Free profit calculator for entrepreneurs.","fields":[
        {"id":"price","label":"Revenue (Monthly)","placeholder":"10000","prefix":"$"},
        {"id":"cost","label":"Cost of Goods Sold","placeholder":"4000","prefix":"$"},
        {"id":"shipping","label":"Operating Expenses","placeholder":"2000","prefix":"$"},
        {"id":"fee","label":"Tax Rate (%)","placeholder":"20","suffix":"%"},
        {"id":"ads","label":"Marketing Spend","placeholder":"1000","prefix":"$"},
    ],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"formula":"Profit = Revenue - (COGS + Operating + Tax% + Marketing)","calc_js":PROFIT_CALC_JS},
    {"slug":"tiktok-shop","title":"TikTok Shop Profit Calculator","desc":"Calculate TikTok Shop profits after platform fees and influencer commissions. Free for TikTok sellers.","fields":[{"id":"price","label":"Selling Price","placeholder":"19.99","prefix":"$"},{"id":"cost","label":"Product Cost","placeholder":"6.00","prefix":"$"},{"id":"shipping","label":"Shipping Cost","placeholder":"3.00","prefix":"$"},{"id":"fee","label":"TikTok Commission (%)","placeholder":"5","suffix":"%"},{"id":"ads","label":"Influencer/Promo Cost","placeholder":"2.00","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"walmart","title":"Walmart Marketplace Profit Calculator","desc":"Calculate Walmart seller profits including referral fees and fulfillment costs.","fields":[{"id":"price","label":"Selling Price","placeholder":"25.00","prefix":"$"},{"id":"cost","label":"Product Cost","placeholder":"10.00","prefix":"$"},{"id":"shipping","label":"Fulfillment & Shipping","placeholder":"4.00","prefix":"$"},{"id":"fee","label":"Walmart Referral Fee (%)","placeholder":"15","suffix":"%"},{"id":"ads","label":"Walmart Ads Cost","placeholder":"1.00","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"mercari","title":"Mercari Profit Calculator","desc":"Calculate Mercari selling profits after selling fees and shipping costs.","fields":[{"id":"price","label":"Selling Price","placeholder":"15.00","prefix":"$"},{"id":"cost","label":"Item Cost","placeholder":"5.00","prefix":"$"},{"id":"shipping","label":"Shipping Cost","placeholder":"4.99","prefix":"$"},{"id":"fee","label":"Mercari Selling Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Promotion Cost","placeholder":"0","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"poshmark","title":"Poshmark Profit Calculator","desc":"Calculate Poshmark profits after 20% commission. Free for Poshmark sellers.","fields":[{"id":"price","label":"Selling Price","placeholder":"30.00","prefix":"$"},{"id":"cost","label":"Item Cost","placeholder":"10.00","prefix":"$"},{"id":"shipping","label":"Shipping Discount Given","placeholder":"0","prefix":"$"},{"id":"fee","label":"Poshmark Fee (%)","placeholder":"20","suffix":"%"},{"id":"ads","label":"Additional Costs","placeholder":"0","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"depop","title":"Depop Profit Calculator","desc":"Calculate Depop selling profits after 10% fee and PayPal processing.","fields":[{"id":"price","label":"Selling Price","placeholder":"25.00","prefix":"$"},{"id":"cost","label":"Item Cost","placeholder":"8.00","prefix":"$"},{"id":"shipping","label":"Shipping Cost","placeholder":"4.00","prefix":"$"},{"id":"fee","label":"Depop Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Promotion Cost","placeholder":"0","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"whatnot","title":"Whatnot Profit Calculator","desc":"Calculate Whatnot live selling profits after commission fees.","fields":[{"id":"price","label":"Selling Price","placeholder":"20.00","prefix":"$"},{"id":"cost","label":"Product Cost","placeholder":"7.00","prefix":"$"},{"id":"shipping","label":"Shipping Cost","placeholder":"4.00","prefix":"$"},{"id":"fee","label":"Whatnot Commission (%)","placeholder":"8","suffix":"%"},{"id":"ads","label":"Giveaway/Promo Cost","placeholder":"0","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"paypal-fee","title":"PayPal Fee Calculator","desc":"Calculate net amount after PayPal fees for business transactions.","fields":[{"id":"price","label":"Transaction Amount","placeholder":"100.00","prefix":"$"},{"id":"fee","label":"PayPal Fee Rate (%)","placeholder":"3.49","suffix":"%"},{"id":"cost","label":"Fixed Fee","placeholder":"0.49","prefix":"$"},{"id":"shipping","label":"","placeholder":"","prefix":"","suffix":""},{"id":"ads","label":"","placeholder":"","prefix":"","suffix":""}],"results":[{"id":"profit","label":"Net After Fees","prefix":"$"},{"id":"margin","label":"Fee Amount","prefix":"$"},{"id":"roi","label":"Effective Rate","prefix":"%"}],"calc_js":"var price=getVal('price'),fee=getVal('fee'),fixed=getVal('cost');var feeAmt=price*(fee/100)+fixed;var net=price-feeAmt;var eff=(feeAmt/price*100);document.getElementById('profit').innerText='$'+net.toFixed(2);document.getElementById('margin').innerText='$'+feeAmt.toFixed(2);document.getElementById('roi').innerText=eff.toFixed(2)+'%';"},
    {"slug":"stripe-fee","title":"Stripe Fee Calculator","desc":"Calculate net revenue after Stripe processing fees. Free for online businesses.","fields":[{"id":"price","label":"Transaction Amount","placeholder":"100.00","prefix":"$"},{"id":"fee","label":"Stripe Fee Rate (%)","placeholder":"2.9","suffix":"%"},{"id":"cost","label":"Fixed Fee","placeholder":"0.30","prefix":"$"},{"id":"shipping","label":"","placeholder":"","prefix":"","suffix":""},{"id":"ads","label":"","placeholder":"","prefix":"","suffix":""}],"results":[{"id":"profit","label":"Net After Fees","prefix":"$"},{"id":"margin","label":"Fee Amount","prefix":"$"},{"id":"roi","label":"Effective Rate","prefix":"%"}],"calc_js":"var price=getVal('price'),fee=getVal('fee'),fixed=getVal('cost');var feeAmt=price*(fee/100)+fixed;var net=price-feeAmt;var eff=(feeAmt/price*100);document.getElementById('profit').innerText='$'+net.toFixed(2);document.getElementById('margin').innerText='$'+feeAmt.toFixed(2);document.getElementById('roi').innerText=eff.toFixed(2)+'%';"},
    {"slug":"print-on-demand","title":"Print on Demand Profit Calculator","desc":"Calculate PoD profits including base cost, shipping, and platform fees.","fields":[{"id":"price","label":"Retail Price","placeholder":"29.99","prefix":"$"},{"id":"cost","label":"Print Provider Cost","placeholder":"12.00","prefix":"$"},{"id":"shipping","label":"Shipping Cost","placeholder":"5.00","prefix":"$"},{"id":"fee","label":"Platform Fee (%)","placeholder":"5","suffix":"%"},{"id":"ads","label":"Design/Mockup Cost","placeholder":"1.00","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"wholesale","title":"Wholesale Profit Calculator","desc":"Calculate wholesale profits with bulk pricing and volume discounts.","fields":[{"id":"price","label":"Wholesale Price per Unit","placeholder":"8.00","prefix":"$"},{"id":"cost","label":"Unit Cost","placeholder":"3.00","prefix":"$"},{"id":"shipping","label":"Shipping per Unit","placeholder":"0.50","prefix":"$"},{"id":"fee","label":"Platform Fee (%)","placeholder":"3","suffix":"%"},{"id":"ads","label":"Storage/Handling","placeholder":"0.25","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit/Unit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"retail-markup","title":"Retail Markup Calculator","desc":"Calculate retail price, markup percentage, and gross profit margin.","fields":[{"id":"cost","label":"Wholesale Cost","placeholder":"20.00","prefix":"$"},{"id":"price","label":"Retail Price","placeholder":"50.00","prefix":"$"},{"id":"shipping","label":"","placeholder":"","prefix":"","suffix":""},{"id":"fee","label":"","placeholder":"","prefix":"","suffix":""},{"id":"ads","label":"","placeholder":"","prefix":"","suffix":""}],"results":[{"id":"profit","label":"Gross Profit","prefix":"$"},{"id":"margin","label":"Margin %","prefix":""},{"id":"roi","label":"Markup %","prefix":"%"}],"calc_js":"var cost=getVal('cost'),price=getVal('price');var profit=price-cost;var margin=cost>0?(profit/price*100):0;var markup=cost>0?((price-cost)/cost*100):0;document.getElementById('profit').innerText='$'+profit.toFixed(2);document.getElementById('margin').innerText=margin.toFixed(1)+'%';document.getElementById('roi').innerText=markup.toFixed(1)+'%';"},
    {"slug":"crypto-trading","title":"Crypto Trading Profit Calculator","desc":"Calculate crypto trading profits including exchange fees and slippage.","fields":[{"id":"price","label":"Sell Price","placeholder":"50000","prefix":"$"},{"id":"cost","label":"Buy Price","placeholder":"48000","prefix":"$"},{"id":"shipping","label":"Investment Amount","placeholder":"1000","prefix":"$"},{"id":"fee","label":"Exchange Fee (%)","placeholder":"0.5","suffix":"%"},{"id":"ads","label":"Gas/Network Fee","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Return %","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"freelance-rate","title":"Freelance Rate Calculator","desc":"Calculate your freelance hourly rate based on desired income and expenses.","fields":[{"id":"price","label":"Desired Annual Income","placeholder":"100000","prefix":"$"},{"id":"cost","label":"Annual Expenses","placeholder":"20000","prefix":"$"},{"id":"shipping","label":"Billable Hours/Year","placeholder":"1500","prefix":""},{"id":"fee","label":"Tax Rate (%)","placeholder":"25","suffix":"%"},{"id":"ads","label":"Benefits/Insurance","placeholder":"10000","prefix":"$"}],"results":[{"id":"profit","label":"Hourly Rate","prefix":"$"},{"id":"margin","label":"Monthly Target","prefix":"$"},{"id":"roi","label":"Take-home","prefix":"$"}],"calc_js":"var income=getVal('price'),exp=getVal('cost'),hours=getVal('shipping'),tax=getVal('fee')/100,benefits=getVal('ads');var needed=income+exp;var gross=needed/(1-tax);var hourly=gross/max(hours,1);var monthly=gross/12;var net=income;document.getElementById('profit').innerText='$'+hourly.toFixed(2);document.getElementById('margin').innerText='$'+monthly.toFixed(0);document.getElementById('roi').innerText='$'+net.toFixed(0);"},
    {"slug":"restaurant","title":"Restaurant Profit Calculator","desc":"Calculate food cost percentage and dish profitability for restaurants.","fields":[{"id":"price","label":"Menu Price","placeholder":"18.00","prefix":"$"},{"id":"cost","label":"Ingredient Cost","placeholder":"5.00","prefix":"$"},{"id":"shipping","label":"Labor per Dish","placeholder":"3.00","prefix":"$"},{"id":"fee","label":"Overhead (%)","placeholder":"30","suffix":"%"},{"id":"ads","label":"Delivery Commission","placeholder":"0","prefix":"$"}],"results":[{"id":"profit","label":"Dish Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"Food Cost %","prefix":"%"}],"calc_js":"var price=getVal('price'),cost=getVal('cost'),labor=getVal('shipping'),fee=getVal('fee')/100,ads=getVal('ads');var overhead=price*fee;var total=cost+labor+overhead+ads;var profit=price-total;var margin=price>0?(profit/price*100):0;var foodCost=cost/price*100;document.getElementById('profit').innerText='$'+profit.toFixed(2);document.getElementById('margin').innerText=margin.toFixed(1)+'%';document.getElementById('roi').innerText=foodCost.toFixed(1)+'%';"},
    {"slug":"real-estate","title":"Real Estate Profit Calculator","desc":"Calculate property investment profits including closing costs and agent fees.","fields":[{"id":"price","label":"Sale Price","placeholder":"350000","prefix":"$"},{"id":"cost","label":"Purchase Price","placeholder":"280000","prefix":"$"},{"id":"shipping","label":"Renovation Cost","placeholder":"30000","prefix":"$"},{"id":"fee","label":"Agent Fee (%)","placeholder":"6","suffix":"%"},{"id":"ads","label":"Closing/Holding Costs","placeholder":"5000","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"ROI %","prefix":""},{"id":"roi","label":"Total Invested","prefix":"$"}],"calc_js":PROFIT_CALC_JS},
    {"slug":"break-even","title":"Break Even Calculator","desc":"Calculate break-even point in units and sales dollars.","fields":[{"id":"cost","label":"Fixed Costs","placeholder":"5000","prefix":"$"},{"id":"price","label":"Price per Unit","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Variable Cost/Unit","placeholder":"20","prefix":"$"},{"id":"fee","label":"","placeholder":"","prefix":"","suffix":""},{"id":"ads","label":"","placeholder":"","prefix":"","suffix":""}],"results":[{"id":"profit","label":"Break-Even Units","prefix":""},{"id":"margin","label":"Break-Even Revenue","prefix":"$"},{"id":"roi","label":"Contrib Margin","prefix":"$"}],"calc_js":"var fixed=getVal('cost'),price=getVal('price'),vc=getVal('shipping');var cm=price-vc;var be_units=cm>0?Math.ceil(fixed/cm):0;var be_rev=be_units*price;document.getElementById('profit').innerText=be_units;document.getElementById('margin').innerText='$'+be_rev.toFixed(0);document.getElementById('roi').innerText='$'+cm.toFixed(2);"},
    {"slug":"facebook-ads","title":"Facebook Ads Profit Calculator","desc":"Calculate Facebook ad campaign ROI and profit. For dropshippers and eCommerce.","fields":[{"id":"price","label":"Revenue from Ads","placeholder":"5000","prefix":"$"},{"id":"cost","label":"Product Cost","placeholder":"2000","prefix":"$"},{"id":"shipping","label":"Ad Spend","placeholder":"1000","prefix":"$"},{"id":"fee","label":"Platform Fee (%)","placeholder":"5","suffix":"%"},{"id":"ads","label":"Creative/VA Cost","placeholder":"200","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"ROAS","prefix":"x"},{"id":"roi","label":"ROI","prefix":""}],"calc_js":"var rev=getVal('price'),cost=getVal('cost'),adspend=getVal('shipping'),fee=getVal('fee')/100,extra=getVal('ads');var feeAmt=rev*fee;var total=cost+adspend+feeAmt+extra;var profit=rev-total;var roas=adspend>0?rev/adspend:0;var roi=total>0?(profit/total*100):0;document.getElementById('profit').innerText='$'+profit.toFixed(2);document.getElementById('margin').innerText=roas.toFixed(1)+'x';document.getElementById('roi').innerText=roi.toFixed(1)+'%';"},
    {"slug":"google-ads","title":"Google Ads Profit Calculator","desc":"Calculate Google Ads ROI and profit per campaign.","fields":[{"id":"price","label":"Campaign Revenue","placeholder":"10000","prefix":"$"},{"id":"cost","label":"Product/Service Cost","placeholder":"4000","prefix":"$"},{"id":"shipping","label":"Ad Spend","placeholder":"2000","prefix":"$"},{"id":"fee","label":"Management Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Landing Page/Tools","placeholder":"300","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"ROAS","prefix":"x"},{"id":"roi","label":"ROI","prefix":""}],"calc_js":"var rev=getVal('price'),cost=getVal('cost'),adspend=getVal('shipping'),fee=getVal('fee')/100,extra=getVal('ads');var total=cost+adspend+rev*fee+extra;var profit=rev-total;var roas=adspend>0?rev/adspend:0;var roi=total>0?(profit/total*100):0;document.getElementById('profit').innerText='$'+profit.toFixed(2);document.getElementById('margin').innerText=roas.toFixed(1)+'x';document.getElementById('roi').innerText=roi.toFixed(1)+'%';"},
    {"slug":"tiktok-ads","title":"TikTok Ads Profit Calculator","desc":"Calculate TikTok ad campaign ROI for dropshipping and eCommerce.","fields":[{"id":"price","label":"Revenue from Ads","placeholder":"3000","prefix":"$"},{"id":"cost","label":"Product Cost","placeholder":"1200","prefix":"$"},{"id":"shipping","label":"Ad Spend","placeholder":"800","prefix":"$"},{"id":"fee","label":"TikTok Fee (%)","placeholder":"2","suffix":"%"},{"id":"ads","label":"Content Creation","placeholder":"200","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"ROAS","prefix":"x"},{"id":"roi","label":"ROI","prefix":""}],"calc_js":"var rev=getVal('price'),cost=getVal('cost'),adspend=getVal('shipping'),fee=getVal('fee')/100,extra=getVal('ads');var total=cost+adspend+rev*fee+extra;var profit=rev-total;var roas=adspend>0?rev/adspend:0;var roi=total>0?(profit/total*100):0;document.getElementById('profit').innerText='$'+profit.toFixed(2);document.getElementById('margin').innerText=roas.toFixed(1)+'x';document.getElementById('roi').innerText=roi.toFixed(1)+'%';"},
    {"slug":"buy-sell","title":"Buy and Sell Profit Calculator","desc":"Calculate flip profit for any item reselling business.","fields":[{"id":"cost","label":"Buy Price","placeholder":"50","prefix":"$"},{"id":"price","label":"Sell Price","placeholder":"120","prefix":"$"},{"id":"shipping","label":"Repair/Shipping","placeholder":"15","prefix":"$"},{"id":"fee","label":"Platform Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Listing/Promo","placeholder":"0","prefix":"$"}],"results":[{"id":"profit","label":"Flip Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"amazon-uk","title":"Amazon UK FBA Profit Calculator","desc":"Calculate UK Amazon FBA profits with UK fees and VAT. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"amazon-canada","title":"Amazon Canada FBA Profit Calculator","desc":"Calculate Canadian Amazon seller profits including GST. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"ebay-uk","title":"eBay UK Profit Calculator","desc":"Calculate eBay UK selling profits including final value fees. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"jewelry","title":"Jewelry Business Profit Calculator","desc":"Calculate jewelry business profits including material costs. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"clothing","title":"Clothing Brand Profit Calculator","desc":"Calculate clothing line profits with manufacturing and shipping. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"handmade","title":"Handmade Products Profit Calculator","desc":"Calculate profits for handmade crafts on Etsy. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"sneakers","title":"Sneaker Reselling Profit Calculator","desc":"Calculate sneaker flip profits with StockX fees. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"books","title":"Book Reselling Profit Calculator","desc":"Calculate used book selling profits on Amazon and eBay. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"electronics","title":"Electronics Reselling Profit Calculator","desc":"Calculate profits from flipping phones and laptops. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"furniture","title":"Furniture Flipping Profit Calculator","desc":"Calculate furniture restoration and resell profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"digital-products","title":"Digital Products Profit Calculator","desc":"Calculate profits from ebooks, courses, and downloads. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"subscription-box","title":"Subscription Box Profit Calculator","desc":"Calculate subscription box business profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"coffee-shop","title":"Coffee Shop Profit Calculator","desc":"Calculate coffee shop drink and food profitability. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"food-truck","title":"Food Truck Profit Calculator","desc":"Calculate food truck operating profits and margins. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"gym","title":"Gym & Fitness Profit Calculator","desc":"Calculate gym membership profit and training margins. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"vending-machine","title":"Vending Machine Profit Calculator","desc":"Calculate vending machine location profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"airbnb","title":"Airbnb Rental Profit Calculator","desc":"Calculate Airbnb rental profits after fees. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"cleaning-business","title":"Cleaning Business Profit Calculator","desc":"Calculate residential cleaning service profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"landscaping","title":"Landscaping Profit Calculator","desc":"Calculate landscaping and lawn care business profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"tutoring","title":"Tutoring Profit Calculator","desc":"Calculate online and in-person tutoring profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"photography","title":"Photography Profit Calculator","desc":"Calculate photography session and wedding profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"bakery","title":"Bakery Profit Calculator","desc":"Calculate bakery product cost and profit per item. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"salon","title":"Hair Salon Profit Calculator","desc":"Calculate salon service pricing and profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"daycare","title":"Daycare Profit Calculator","desc":"Calculate home daycare and childcare center profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"plumbing","title":"Plumbing Profit Calculator","desc":"Calculate plumbing service call profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"electrician","title":"Electrician Profit Calculator","desc":"Calculate electrical service job profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"hvac","title":"HVAC Profit Calculator","desc":"Calculate HVAC installation and repair job profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"roofing","title":"Roofing Profit Calculator","desc":"Calculate roofing job profits including materials. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"saas-mrr","title":"SaaS MRR Profit Calculator","desc":"Calculate SaaS monthly recurring revenue and churn. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"youtube-channel","title":"YouTube Channel Profit Calculator","desc":"Calculate YouTube ad revenue profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"podcast","title":"Podcast Profit Calculator","desc":"Calculate podcast sponsorship and ad revenue profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"newsletter","title":"Email Newsletter Profit Calculator","desc":"Calculate paid newsletter and sponsorship revenue. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"marketing-agency","title":"Marketing Agency Profit Calculator","desc":"Calculate agency retainer profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"web-designer","title":"Web Design Profit Calculator","desc":"Calculate web design project profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"virtual-assistant","title":"Virtual Assistant Profit Calculator","desc":"Calculate VA service hourly profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"stock-trader","title":"Stock Trading Profit Calculator","desc":"Calculate stock trading profits. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"dividend-calc","title":"Dividend Income Profit Calculator","desc":"Calculate dividend investment income. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"freelance-writer","title":"Freelance Writing Profit Calculator","desc":"Calculate freelance writing income and hourly rates.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"graphic-designer","title":"Graphic Design Profit Calculator","desc":"Calculate graphic design project profits and pricing.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"video-editor","title":"Video Editing Profit Calculator","desc":"Calculate video editing and production project profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"music-producer","title":"Music Production Profit Calculator","desc":"Calculate music production and beat-selling profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"car-flipping","title":"Car Flipping Profit Calculator","desc":"Calculate used car buying and reselling profit margins.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"domain-flipping","title":"Domain Flipping Profit Calculator","desc":"Calculate domain name buying and selling profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"website-flipping","title":"Website Flipping Profit Calculator","desc":"Calculate website buying, improving, and reselling profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"nft-trading","title":"NFT Trading Profit Calculator","desc":"Calculate NFT minting and trading profits after gas fees.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"airbnb-experience","title":"Airbnb Experience Profit Calculator","desc":"Calculate Airbnb experience hosting profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"rental-property","title":"Rental Property Profit Calculator","desc":"Calculate long-term rental property cash flow and profit.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"house-flipping","title":"House Flipping Profit Calculator","desc":"Calculate fix-and-flip house project profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"commercial-realestate","title":"Commercial Real Estate Profit Calculator","desc":"Calculate commercial property investment profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"atm-business","title":"ATM Business Profit Calculator","desc":"Calculate ATM route and placement business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"ice-machine","title":"Ice Machine Profit Calculator","desc":"Calculate ice vending machine business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"parking-lot","title":"Parking Lot Profit Calculator","desc":"Calculate parking lot and garage business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"rv-rental","title":"RV Rental Profit Calculator","desc":"Calculate RV and camper rental business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"boat-rental","title":"Boat Rental Profit Calculator","desc":"Calculate boat and watercraft rental profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"equipment-rental","title":"Equipment Rental Profit Calculator","desc":"Calculate construction equipment rental profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"self-storage","title":"Self Storage Profit Calculator","desc":"Calculate self-storage facility development profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"trailer-park","title":"Mobile Home Park Profit Calculator","desc":"Calculate mobile home park investment returns.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"billboard","title":"Billboard Advertising Profit Calculator","desc":"Calculate billboard rental and advertising profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"coworking","title":"Coworking Space Profit Calculator","desc":"Calculate coworking space membership and rental profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"ghost-kitchen","title":"Ghost Kitchen Profit Calculator","desc":"Calculate delivery-only restaurant kitchen profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"meal-prep","title":"Meal Prep Business Profit Calculator","desc":"Calculate weekly meal prep service profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"juice-bar","title":"Juice/Smoothie Bar Profit Calculator","desc":"Calculate juice and smoothie bar drink profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"boba-shop","title":"Boba Tea Shop Profit Calculator","desc":"Calculate bubble tea shop drink profitability.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"pizza-shop","title":"Pizza Shop Profit Calculator","desc":"Calculate pizzeria profit per pizza and delivery.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"food-stall","title":"Food Stall/Fair Profit Calculator","desc":"Calculate fair and market food stall profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"candle-business","title":"Candle Making Profit Calculator","desc":"Calculate handmade candle business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"soap-business","title":"Soap Making Profit Calculator","desc":"Calculate handmade soap and skincare profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"dog-treats","title":"Pet Treats Business Profit Calculator","desc":"Calculate homemade dog treat business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"tshirt-business","title":"T-Shirt Business Profit Calculator","desc":"Calculate custom t-shirt printing and selling profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"sticker-business","title":"Sticker Business Profit Calculator","desc":"Calculate vinyl sticker and decal business profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"3d-printing","title":"3D Printing Profit Calculator","desc":"Calculate 3D printing service and product profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"laser-engraving","title":"Laser Engraving Profit Calculator","desc":"Calculate laser engraving business project profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"embroidery","title":"Embroidery Business Profit Calculator","desc":"Calculate custom embroidery and apparel profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
    {"slug":"woodworking","title":"Woodworking Profit Calculator","desc":"Calculate woodworking and custom furniture profits.. Free for entrepreneurs.","fields":[{"id":"price","label":"Revenue","placeholder":"100","prefix":"$"},{"id":"cost","label":"Cost","placeholder":"50","prefix":"$"},{"id":"shipping","label":"Expenses","placeholder":"10","prefix":"$"},{"id":"fee","label":"Fee (%)","placeholder":"10","suffix":"%"},{"id":"ads","label":"Other","placeholder":"5","prefix":"$"}],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS},
]

HOMEPAGE = {"title":"Free Profit Calculator for eCommerce Sellers","desc":"Calculate profit margins, fees, and ROI for Amazon FBA, Etsy, eBay, Shopify, and dropshipping. Free, no sign-up.","slug":"","fields":[
    {"id":"price","label":"Selling Price","placeholder":"29.99","prefix":"$"},
    {"id":"cost","label":"Product Cost","placeholder":"10.00","prefix":"$"},
    {"id":"shipping","label":"Shipping Cost","placeholder":"5.00","prefix":"$"},
    {"id":"fee","label":"Platform Fee (%)","placeholder":"10","suffix":"%"},
    {"id":"ads","label":"Ad Spend per Unit","placeholder":"3.00","prefix":"$"},
],"results":[{"id":"profit","label":"Net Profit","prefix":"$"},{"id":"margin","label":"Profit Margin","prefix":""},{"id":"roi","label":"ROI","prefix":""}],"calc_js":PROFIT_CALC_JS}

ALL_SCENARIOS = PLATFORMS

def build_home():
    html = build_page(HOMEPAGE, is_home=True)
    w("index.html", html)
    print("🏠 index.html")

def build_scenes():
    for s in ALL_SCENARIOS:
        html = build_page(s)
        w(f"{s['slug']}/index.html", html)
        print(f"  📄 {s['slug']}/")

def build_sitemap():
    import os
    urls = [f"https://{DOMAIN}/"]
    for root, dirs, files in os.walk('.'):
        for f in files:
            if f == 'index.html' and root != '.':
                rel = os.path.relpath(root, '.').replace('\\', '/')
                if not rel.startswith('.') and not rel.startswith('.git'):
                    urls.append(f"https://{DOMAIN}/{rel}/")
    lines = ['<?xml version="1.0" encoding="UTF-8"?>']
    lines.append('<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">')
    for u in urls:
        p = "1.0" if u == f"https://{DOMAIN}/" else "0.8"
        lines.append(f'  <url><loc>{u}</loc><changefreq>weekly</changefreq><priority>{p}</priority></url>')
    lines.append('</urlset>')
    with open('sitemap.xml', 'w') as f:
        f.write('\n'.join(lines))
    print(f"📄 sitemap.xml ({len(urls)} URLs)")

def build_robots():
    w("robots.txt", f"User-agent: *\nAllow: /\nSitemap: https://{DOMAIN}/sitemap.xml\n")
    print("🤖 robots.txt")

def build_static():
    w("privacy.html", "<h1>Privacy</h1><p>ProfitCalc does not collect or store personal data. All calculations happen in your browser.</p>")
    w("terms.html", "<h1>Terms</h1><p>Free tool. Calculations are estimates. Verify with your platform.</p>")
    w("contact.html", "<h1>Contact</h1><p>For questions, reach out via the domain contact form.</p>")
    w("404.html", "<h1>404</h1><p>Page not found. <a href='/'>Back to ProfitCalc</a></p>")

if __name__ == "__main__":
    build_home()
    print(f"\n📄 6 Calculator Pages:")
    build_scenes()
    build_sitemap()
    build_robots()
    build_static()
    print(f"\n✅ Build Complete — {len(ALL_SCENARIOS) + 5} pages")
